name: BK-TEST

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGO_DB_TEST: ${{ secrets.MONGO_DB_TEST }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRE: ${{ secrets.JWT_EXPIRE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Nest.js application
        run: npm run build
